=== DANXOMG/Backup_clases/Lenguaje de Marcas/ejercicios_examen/xsd/recuperacion/xsd/prueba1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!--Cometario-->
<xs:annotation>
    <xs:documentation>
        Esto es una biblioteca
    </xs:documentation>
</xs:annotation>

<xs:element name="biblioteca">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="libro">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="titulo"/>
                        <xs:element name="autor"/>
                        <xs:element name="aÃ±o"/>
                        <xs:element name="editorial"/>
                    </xs:sequence>
                </xs:complexType>

            </xs:element>
        </xs:sequence>
        <xs:attribute name="cod" type="xs:string"/>
    </xs:complexType>
</xs:element>



</xs:schema>

=== DANXOMG/Backup_clases/Lenguaje de Marcas/ejercicios_examen/xsd/recuperacion/xsd/prueba1.xml
<?xml version="1.0" encoding="UTF-8"?>

<biblioteca xmlns:xs="http://www.w3.org/2001/XMLSchema" xs:noNamespaceSchemaLocation="prueba1.xsd">
    <libro cod="01">
        <titulo>La colmena</titulo>
        <autor>Camilo Jose Cela</autor>
        <año>2005</año>
        <editorial>Rama</editorial>
    </libro>
    <libro cod="02">
        <titulo>Las hijas del capitan</titulo>
        <autor>María Dueñas</autor>
        <año>2020</año>
        <editorial>Planeta</editorial>
    </libro>
    <libro cod="03">
        <titulo>Esperanza</titulo>
        <autor>Damielle Steel</autor>
        <año>2018</año>
        <editorial>Anaya</editorial>
    </libro>
</biblioteca>
